spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: MZXeBPP4PTZfJo2RSCT1
            client-secret: 7cnyhK5q2n
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-name: Naver
          kakao:
            client-id: caa6ede2ff77cc3cb649e9e3b0975b73
            client-secret: n1rODEb37ka2jbRlBsgqvMKSFDDj8Kzs
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  servlet:
    session:
      timeout: 24h
